(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'f5f8b242-e2dc-4a72-873a-c50da511cee9-map-container',
          componentName:'MapRaw5',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:""
        });
      })({"isPublishMode":true,"lat":"22.5703039","lon":"88.3495653","address":"Dalhousie Square, RN Mukherjee Road, Lal Dighi, Lal Bazar, Kolkata, West Bengal, India","type":"google","isEditMode":false,"zoom":14,"env":"production","mapboxAccessToken":"pk.eyJ1IjoiZ29kYWRkeSIsImEiOiJjaWc5b20wcjcwczAydGFsdGxvamdvYnV0In0.JK9HuO6nAzc8BnMv6W7NBQ","mapboxStyleUrl":"mapbox:\u002F\u002Fstyles\u002Fgodaddy\u002Fciovyeygh0029atm6zbntgxk2","staticContent":{"today":"Today","submitButtonLoadingLabel":"Sending","contactFormResponseErrorMessage":"Something went wrong while sending your message, please try again later","defaultCancelButtonLabel":"Cancel","byAppointment":"By Appointment","defaultSubmitButtonLabel":"Send","closed":"Closed","termsOfSerivce":"Terms of Service","recaptchaDisclosure":"This site is protected by reCAPTCHA and the Google {privacyPolicy} and {termsOfSerivce} apply.","emailValidationErrorMessage":"Please enter a valid email address.","mapCTA":"Get directions","privacyPolicyURL":"https:\u002F\u002Fpolicies.google.com\u002Fprivacy","requiredValidationErrorMessage":"Please fill in this required field","openToday":"Open today","privacyPolicy":"Privacy Policy","termsOfSerivceURL":"https:\u002F\u002Fpolicies.google.com\u002Fterms"},"viewDevice":null,"widgetId":"f5f8b242-e2dc-4a72-873a-c50da511cee9","section":"default","category":"neutral","locale":"en-IN","renderMode":"PUBLISH"},{"widgetId":"f5f8b242-e2dc-4a72-873a-c50da511cee9","widgetType":"CONTACT","widgetPreset":"contact5","section":"default","category":"neutral","fontSize":"medium","fontFamily":"alternate","group":"Map","groupType":"Banner"});