(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'f5f8b242-e2dc-4a72-873a-c50da511cee9-bootstrap-container',
          componentName:'ContactForm5',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:""
        });
      })({"formTitle":"Contact Us Right-away","formFields":[{"type":"SINGLE_LINE","label":"Name","required":false},{"type":"EMAIL","label":"Email","validation":"email","required":true,"replyTo":true},{"label":"What is Company's Name","type":"SINGLE_LINE","required":false},{"type":"MULTI_LINE","label":"Tell us your Phone No.","required":true},{"label":"Tell your Query","type":"SINGLE_LINE","required":false},{"type":"SUBMIT","label":"Send","required":false}],"blankInfo":false,"formSubmitHost":"https:\u002F\u002Fcontact.apps-api.instantpage.secureserver.net","showMap":true,"recaptchaEnabled":true,"recaptchaType":"V3","domainName":"nidhi.fincodetech.in","formSuccessMessage":"Thank you for your inquiry! We will get back to you within 48 hours.","formEnabled":true,"websiteId":"e6ff78d7-45fa-4077-bd2d-3cac5d162ac8","pageId":"19756ec4-e4cf-4fdf-a713-8a76c75f0b75","accountId":"64e39081-8a17-11ea-81ca-3417ebe72595","staticContent":{"today":"Today","submitButtonLoadingLabel":"Sending","contactFormResponseErrorMessage":"Something went wrong while sending your message, please try again later","defaultCancelButtonLabel":"Cancel","byAppointment":"By Appointment","defaultSubmitButtonLabel":"Send","closed":"Closed","termsOfSerivce":"Terms of Service","recaptchaDisclosure":"This site is protected by reCAPTCHA and the Google {privacyPolicy} and {termsOfSerivce} apply.","emailValidationErrorMessage":"Please enter a valid email address.","mapCTA":"Get directions","privacyPolicyURL":"https:\u002F\u002Fpolicies.google.com\u002Fprivacy","requiredValidationErrorMessage":"Please fill in this required field","openToday":"Open today","privacyPolicy":"Privacy Policy","termsOfSerivceURL":"https:\u002F\u002Fpolicies.google.com\u002Fterms"},"emailOptInEnabled":false,"emailOptInHidden":false,"emailOptInMessage":"Sign up for our email list for updates, promotions, and more.","emailConfirmationMessage":"We've sent you a confirmation email, please click the link to verify your address.","widgetId":"f5f8b242-e2dc-4a72-873a-c50da511cee9","section":"default","category":"neutral","locale":"en-IN","renderMode":"PUBLISH"},{"widgetId":"f5f8b242-e2dc-4a72-873a-c50da511cee9","widgetType":"CONTACT","widgetPreset":"contact5","section":"default","category":"neutral","fontSize":"medium","fontFamily":"alternate","group":"Content","groupType":"Default"});