(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'bs-8',
          componentName:'NavOverflow',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:""
        });
      })({"style":{"marginHorizontal":"-6px","marginVertical":"-6px","paddingHorizontal":"6px","paddingVertical":"6px"},"activeStyle":{"marginHorizontal":"-6px","marginVertical":"-6px","paddingHorizontal":"6px","paddingVertical":"6px"},"label":"More","parentId":"n-4651046519-navId","toggleId":"46520-moreId","navBarId":"navBarId-46518","logoImageId":"logo-46517","navigation":[{"isFlyoutMenu":false,"active":false,"pageId":"c0844dd4-becf-421c-bdf5-aa0311594920","name":"Home","href":"\u002F","target":"","visible":true,"requiresAuth":false,"tags":[],"rel":"","type":"page","showInFooter":true},{"isFlyoutMenu":false,"active":false,"pageId":"25a1c4fa-cc01-4777-9611-9a1bbc99bbe9","name":"Software features","href":"\u002Fsoftware-features","target":"","visible":true,"requiresAuth":false,"tags":[],"rel":"","type":"page","showInFooter":true},{"isFlyoutMenu":false,"active":false,"pageId":"9e01a914-ba34-4c78-8de8-16342e4d514e","name":"Plan Pricing","href":"\u002Fplan-pricing","target":"","visible":true,"requiresAuth":false,"tags":[],"rel":"","type":"page","showInFooter":true},{"isFlyoutMenu":false,"active":false,"pageId":"64aec41a-b5aa-4749-a17a-3885080d71db","name":"Book free Demo","href":"\u002Fbook-free-demo","target":"","visible":true,"requiresAuth":false,"tags":[],"rel":"","type":"page","showInFooter":true},{"isFlyoutMenu":false,"active":true,"pageId":"19756ec4-e4cf-4fdf-a713-8a76c75f0b75","name":"Contact Us","href":"\u002Fcontact-us","target":"","visible":true,"requiresAuth":false,"tags":[],"rel":"","type":"page","showInFooter":true}],"staticContent":{"hamburgerIcon":"Hamburger Site Navigation Icon","YouTube":"YouTube Social Link","Facebook":"Facebook Social Link","carouselAddImageHelper":"Click Here to Add Images to Slideshow!","membershipSectionTitle":"Account","membershipSignedInStatus":"Signed in as:","Xing":"Xing Social Link","membershipSignedOutStatus":"Currently not signed in","Houzz":"Houzz Social Link","morePages":"More","membershipBookings":"Bookings","Yelp":"Yelp Social Link","Google+":"Google Plus Social Link","Instagram":"Instagram Social Link","Twitter":"Twitter Social Link","translateBarHelper":"Translate: ","promoBannerLink":"Promotion Banner Link","membershipAccount":"My Account","membershipSignIn":"Sign In","cartIcon":"Shopping Cart Icon","Pinterest":"Pinterest Social Link","membershipCreateAccount":"Create Account","membershipOrders":"Orders","membershipSignOut":"Sign out","membershipSignOutCaps":"SIGN OUT","search_placeholder":"Search Products","LinkedIn":"LinkedIn Social Link"},"widgetId":"e135ba03-ed6a-4df7-8b69-f82932cddb27","section":"alt","category":"neutral","locale":"en-IN","renderMode":"PUBLISH"},{"widgetId":"e135ba03-ed6a-4df7-8b69-f82932cddb27","widgetType":"HEADER","widgetPreset":"header9","section":"alt","category":"neutral","fontSize":"medium","fontFamily":"alternate","group":"Nav","groupType":"Default"});